Build on top of cuda and tensorflow containers
alan-turing-institute/CuCalc pull request #3
Opened 2020-09-11 09:24 UTC by JimMadge

This is a change in strategy. The official CoCalc Dockerfile is modified to be based on the tensorflow container (which in turn is based on the cuda container). The advantage is it removes the burden of maintaining the correct, specific versions of cuda/tensorflow dependencies which seemed to be the biggest barrier when we were trying to add these to the CoCalc image.

This means the repository is a recipe for making a Dockerfile rather than the Dockerfile itself.

The downside of this approach is the build times are significantly longer.

2020-09-11 09:37 UTC, crmne commented
That's cool, but I think there should be a "compiled" `Dockerfile` so Docker Hub can create a build. Perhaps it's worth considering adding it as a pre-commit hook: https://pre-commit.com/

2020-09-14 14:45 UTC, JimMadge commented
> That's cool, but I think there should be a "compiled" `Dockerfile` so Docker Hub can create a build. Perhaps it's worth considering adding it as a pre-commit hook: https://pre-commit.com/

Good idea. I did think about making this part of CI, but having a Dockerfile people can see and use in the repository would be better.

2020-09-16 14:40 UTC, JimMadge commented
@jemrobinson I think this may be ready for review now. I have added,
- a git hook to build an up to date Dockerfile pre-commit 
- a step in the CI to check this
- a CI build test
- a CI job to push tagged commits to DockerHub (as yet untested)
- some guidance in the README.md

2020-09-16 16:05 UTC, jemrobinson requested changes
Looks good. A couple of minor comments/changes. Also, do we understand why theano doesn't work? Is this something we should open as a new issue?

2020-09-16 16:05 UTC, jemrobinson commented on Dockerfile
> +MAINTAINER William Stein <wstein@sagemath.com>
Should we find-and-replace this line when we construct the Dockerfile?

2020-09-16 16:05 UTC, jemrobinson commented on Dockerfile
> +RUN pip3 install theano keras torch
Can you restore the `IJulia` section from the `1-update-cuda` branch

2020-09-16 16:05 UTC, jemrobinson commented on README.md
> +CoCalc rebased ontop of tensorflow and cuda.
```suggestion
CoCalc rebased on top of tensorflow and CUDA.
```

2020-09-16 16:05 UTC, jemrobinson commented on README.md
> +Clone this repository *and* the cocalc-docker subrepository
```suggestion
Clone this repository *and* the `cocalc-docker` repository
```

2020-09-17 07:21 UTC, JimMadge commented on Dockerfile
> +MAINTAINER William Stein <wstein@sagemath.com>
Yes, looks like the `MAINTAINER` key is [deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) as well.

2020-09-17 07:30 UTC, JimMadge commented on README.md
> +Clone this repository *and* the cocalc-docker subrepository
I will change 'subrepository' to 'submodule' but I want to avoid saying repository as specifically cocalc is a submodule fixed at a particular commit hash. I don't want to confuse this with cloning `cocalc-docker` at master.

2020-09-17 08:33 UTC, JimMadge commented on README.md
> +Clone this repository *and* the cocalc-docker subrepository
fixed in 925e34a5a90a770c3f0b71c535f6850b26bac310

2020-09-17 08:34 UTC, JimMadge commented on Dockerfile
> +RUN pip3 install theano keras torch
Fixed in 8f0b2df8df2b7bd08702be745bb2989b0f681d60

2020-09-17 08:34 UTC, JimMadge commented on Dockerfile
> +MAINTAINER William Stein <wstein@sagemath.com>
Fixed in 9986ca2258ef527939b716b2bc7fe5c3d43fc50a

2020-09-17 12:56 UTC, jemrobinson commented
[In this recent log](https://pipelines.actions.githubusercontent.com/aROPbZffBDSrb0Birs6E7qz9CEG40QJbJHsSn6aQ2llxfYPljs/_apis/pipelines/1/runs/13/signedlogcontent/3?urlExpires=2020-09-17T12%3A37%3A07.6721161Z&urlSigningMethod=HMACV1&urlSignature=bXwTewuRA8uZo7wDfkg%2B1aV%2BQJbCwVA25ULixlJ3TMs%3D) it looks like the IJulia installation is failing. The relevant lines are:

```
2020-09-17T12:11:39.6828883Z Step 39/56 : RUN julia -e 'ENV["JUPYTER"] = "/usr/local/bin/jupyter"; #ENV["JULIA_PKGDIR"] = "/opt/julia/share/julia/site"; using Pkg; Pkg.add("IJulia");'   && mv /root/.local/share/jupyter/kernels/julia-* /usr/local/share/jupyter/kernels
2020-09-17T12:11:39.7101259Z  ---> Running in 539a9e444d62
2020-09-17T12:11:42.1718734Z [91mmv: cannot stat '/root/.local/share/jupyter/kernels/julia-*': No such file or directory
2020-09-17T12:11:42.3969236Z The command '/bin/bash -c julia -e 'ENV["JUPYTER"] = "/usr/local/bin/jupyter"; #ENV["JULIA_PKGDIR"] = "/opt/julia/share/julia/site"; using Pkg; Pkg.add("IJulia");'   && mv /root/.local/share/jupyter/kernels/julia-* /usr/local/share/jupyter/kernels' returned a non-zero code: 1
2020-09-17T12:11:42.4056986Z make: *** [build] Error 1
2020-09-17T12:11:42.4058421Z [0mMakefile:14: recipe for target 'build' failed
2020-09-17T12:11:42.4481463Z ##[error]Process completed with exit code 2.
```

Is this process running as root? If not, that might explain why `/root/.local/share/jupyter/kernels/julia-*` does not exist. Do you have a local build that you can use to debug this @JimMadge ?

2020-09-17 13:25 UTC, JimMadge commented
> Do you have a local build that you can use to debug this @JimMadge ?

Doing this currently. Given it takes a long time to build, I probably should have done that first.

I would be very surprised if it were not running as root.

2020-09-21 12:26 UTC, jemrobinson commented on Makefile
> +	sed -i'' 's|^MAINTAINER .*|LABEL maintainer="researchengineering@turing.ac.uk"|' Dockerfile
What does `sed -i''` do that `sed -i` doesn't?

2020-09-21 12:27 UTC, jemrobinson commented on README.md
> +This repository contains a Git hook to build and add a `Dockerfile` upon each
```suggestion
This repository contains a Git hook to update the `Dockerfile` upon each
```

2020-09-21 13:47 UTC, JimMadge commented on Makefile
> +	sed -i'' 's|^MAINTAINER .*|LABEL maintainer="researchengineering@turing.ac.uk"|' Dockerfile
Nothing for GNU sed, but BSD sed complains if `-i` has no argument.

2020-09-22 09:48 UTC, jemrobinson commented on Makefile
> +	sed -i'' 's|^MAINTAINER .*|LABEL maintainer="researchengineering@turing.ac.uk"|' Dockerfile
OK, then maybe it's worth adding `-e` before the replace commands to be explicit that this is a different command?

2020-09-22 09:48 UTC, jemrobinson approved these changes

2020-09-22 13:39 UTC, merged